repos:
  - repo: local
    hooks:
    -   id: black
        name: black
        entry: black --line-length=120
        language: system
        files: \.py$
        stages: [commit]
        types: [python]

    -   id: pylint
        name: PyLint
        entry: python -m pylint --rcfile=.pylintrc
        language: system
        files: \.py$
        stages: [commit]
